### ISSUE TITLE
Can't Debug Locally - Missing Files

### ISSUE THREAD

**Issue by pmgower** [nathanwoulfe/PieMan#14]
I currently have a version of PieMan working on an Umbraco v7.5.6 site without issues.  However, when I upgraded the site to v7.6.8 PieMan stopped working.  Also some of our clients want some new features added to PieMan so I was going to customize it and upgrade to the latest version of Skybrud.Social to see if that solved the issue with the latest version of Umbraco.

However, when I cloned the repo and opened up the csproj file in Visual Studio I noticed there was a missing **packages.config** file and the **solution file** was missing as well.  I also noticed there were some files that were checked into the git repo but not included in the csproj file (e.g. 2 controllers, 3 model files, SkybudSocialExtensionMethods folder, etc.).

So I wanted to check and see if @nathanwoulfe is still maintaining this plugin because I love what we have so far.  I just wanted to make some minor modifications and use it with an upgraded Umbraco site.

Also I was curious what the benefit is of using **Skybrud.Social** over the **Google Analytics API Client Library for .NET**

**Comment by nathanwoulfe** [comment]
Haven't looked at this in quite a while - whole package probably needs a bit of a tidy up. 

Will find why it's not working and get a patch out, but will also start on a refactor for a major version release.

**Comment by pmgower** [comment]
@nathanwoulfe I'd like to help with that if possible.  Let me know what I can do.  If I can get those missing files I might be able to get it working on my end locally and start helping sooner than later.

**Comment by nathanwoulfe** [comment]
@pmgower I've just pushed up a substantial refactor - updated a heap of dependencies etc, removed stale stuff, should be working on 7.x again now. It's still a bit stinky, but can be improved incrementally.

I used Skybrud instead of the standard Google library as it abstracts away a lot of the fiddly bits, and just provides a simple API for access the endpoints I need. Updated this to the latest version, which is cleaner still.

I'm working on getting CD/CI set up, thought it was sorted but I'm still missing some files in the final build. Should have that resolved tomorrow hopefully. Need to find out how to include a dependency in the nuget build too, then it should be all peachy.

**Comment by nathanwoulfe** [comment]
@pmgower should be good to go - https://ci.appveyor.com/project/nathanwoulfe/pieman/build/artifacts is the latest packaged build, and the repo is much cleaner and carrying less dead weight

Still a couple of minor things to fix, but in much better shape than it was a week ago... Feel free to submit any changes as a PR, more than happy to take contributions.

**Comment by adkwatt** [comment]
I've been working with @pmgower using this new version and I'm having a configuration issue.  In the settings function of pieman.js (line 359) it checks to see if there is a refresh token and if so, assumes there is an account and profile to pull.  When I try to run it, it has a refresh token from somewhere but no account or profile because the auth and config never happened.  I'm not sure where the refresh token is coming from or where it is stored.

Edit:  It may be an Umbraco versioning issue.  This is an older site on 7.6.8 and I see you are recommending >= 7.7.

**Comment by nathanwoulfe** [comment]
It should be fine on 7.6.x, I bumped the version number really so I wasn't having to consider really old stuff.

I've pushed a new version, my build was not picking up the correct files (wasn't cleaning before packaging), but I don't think that will have anything to with your issue. Is this a fresh install or has it been upgraded?

**Comment by adkwatt** [comment]
I'm trying to upgrade an existing install.  I reset the prevalues in the database to the defaults but that didn't seem to fix it.

**Comment by nathanwoulfe** [comment]
That's odd - the only place I'm storing the refresh token is as a prevalue on the datatype. Could try uninstall then reinstall, there could be old files hanging around from the previous version, but again, those wouldn't be storing the token.

Other option would be to try revoking the Google auth, but if there's a stray token you won't get the option to re-auth in Umbraco... 

Will have another look

**Comment by nathanwoulfe** [comment]
The only place that could be coming from is the prevalue on the property editor. See what happens if you uninstall and reinstall...
